Code refactoring
sindresorhus/boxen pull request #58
Opened 2021-08-30 01:03 UTC by Caesarovich

This PR has for objective to provide a little code refactoring in order to make the library more easily maintainable/scalable/readable.
Effectively the main function of the library was around 150 lines long and it renders it really hard to read/understand.

So I decided to divide it a little, now the code is separated into two 'main functions' : 
- The main function from before without the content handling part.
- And the makeContentText function wich now handles the whole content part.

This new function takes in 4 arguments: 
- text: wich is the box's content text provided by the user
- padding: the optional padding desired
- columns: the maximum column count the content should take
- align: the optional text alignment

This allows for more flexibility regarding the width of the content. It'll allow an easy implementation for issue #51. (PR coming soon). Also the way this function is done/used fixes issue #53 and all kind of similar bugs where the box would exceed the terminal's size. See images below:

![Image comparison of old/new version](https://i.imgur.com/jzKJ95V.png)

This pretty much sums up the purpose of this PR. It's kind of a preparation for other PRs I'm preparing

2021-09-05 12:29 UTC, sindresorhus requested changes

2021-09-05 12:29 UTC, sindresorhus commented on index.js
> +		const marWidth = Math.max((columns - contentWidth - BORDERS_WIDTH) / 2, 0);
```suggestion
		const marginWidth = Math.max((columns - contentWidth - BORDERS_WIDTH) / 2, 0);
```

2021-09-05 12:29 UTC, sindresorhus commented
> Remove outdated tests that aren't relevant anymore

Why are the tests not relevant anymore?

2021-09-05 12:30 UTC, sindresorhus commented
> Also the way this function is done/used fixes #53 and all kind of similar bugs where the box would exceed the terminal's size.

Would be nice to have tests for this.

2021-09-06 00:15 UTC, Caesarovich commented
> > Remove outdated tests that aren't relevant anymore
> 
> Why are the tests not relevant anymore?

Those tests were expecting results that do not accord with the fact that the boxes shouldn't overflow the terminal.

I found that by investigating those and try running them in a separate script. I observed that the test produced a box exceeding the terminal's size and accounting it as Ok, while accounting the new version (The one that doesn't overflow anymore) as Ko.
It's due to the fact that the new way of doing the box I implemented works very differently than before in some ways, like cutting the text into newlines to not overflow, etc...

2021-09-06 00:16 UTC, Caesarovich commented
> > Also the way this function is done/used fixes #53 and all kind of similar bugs where the box would exceed the terminal's size.
> 
> Would be nice to have tests for this.

This is a very good idea, I'll get to it.

2021-09-06 01:40 UTC, Caesarovich commented
Changes done, waiting for your review 👍

2021-09-06 11:18 UTC, sindresorhus commented
> Those tests were expecting results that do not accord with the fact that the boxes shouldn't overflow the terminal.

Wouldn't it be better to adjust the tests instead of removing them?

2021-09-06 11:52 UTC, Caesarovich commented
Changes done, waiting for your review 

> > Those tests were expecting results that do not accord with the fact that the boxes shouldn't overflow the terminal.
> 
> Wouldn't it be better to adjust the tests instead of removing them?

I can do it. Tho the it is now equivalent as combining the 'align option' tests with the new 'overflow' test. If anything, one one these two would already Ko before.

I'll push it in the next minutes.

2021-09-06 12:12 UTC, Caesarovich commented
Readapted the tests. I pushed the changes.  👌

2021-09-06 13:54 UTC, sindresorhus commented on test.js
> +	lines.forEach(line => {
I prefer using `for-of` instead of `.forEach`.

2021-09-06 13:54 UTC, sindresorhus commented on test.js
> +	const checkAlign = (index, leftPad, rightPad) => {
```suggestion
	const checkAlign = ({index, leftPad, rightPad}) => {
```

To improve readability at the callsite.

2021-09-06 14:27 UTC, merged

2021-09-06 14:27 UTC, sindresorhus commented
Looks good now. Thanks :)