Feature: height and fullscreen option
sindresorhus/boxen pull request #75
Opened 2022-05-13 15:48 UTC by Caesarovich

In answer to #29 , here I have added an height constraint option and a fullscreen option.

Example with height option:

```js
import boxen from 'boxen';

console.log(boxen('foo bar', {height: 5}));
// ┌───────┐
// │foo bar│
// │       │
// │       │
// └───────┘
```

Sorry for the wait, I have found a job and couldn't find many time to focus on this issue.

---

Fixes #29

2022-05-13 16:45 UTC, sindresorhus commented
// @LitoMore

2022-05-14 13:39 UTC, Caesarovich commented
@sindresorhus Should we really wait for @LitoMore ? The features are there and working as expected ;)

2022-05-14 13:45 UTC, LitoMore commented
> @sindresorhus Should we really wait for @LitoMore ? The features are there and working as expected ;)

I will take a look.

2022-05-14 15:43 UTC, LitoMore commented
Please add some tests for the `fullscreen` option.

BTW, as we discussed before at https://github.com/sindresorhus/boxen/issues/29#issuecomment-950273311, the `fullscreen` option should be able to accept a function for modifications.

2022-05-14 15:51 UTC, LitoMore commented on index.d.ts
> +
```suggestion
```

2022-05-14 15:51 UTC, LitoMore commented on index.d.ts
> +
I think `width` and `height` should have higher priority. Then users can create a full-width or full-height box without difficulty.

2022-05-14 15:52 UTC, LitoMore commented
Readme needs to be updated.

2022-05-15 16:34 UTC, sindresorhus commented on index.d.ts
> +	**Note*: This option will crop overflowing content.
```suggestion
	__Note__: This option will crop overflowing content.
```

2022-05-15 18:20 UTC, Caesarovich commented
@LitoMore I'm wondering if having the possibility to use a function as argument isn't too much complexity for little benefits

2022-05-19 01:25 UTC, LitoMore commented
> I'm wondering if having the possibility to use a function as argument isn't too much complexity for little benefits


See https://github.com/sindresorhus/boxen/issues/29#issuecomment-950273311.

2022-05-25 07:42 UTC, Caesarovich commented
// @LitoMore

2022-05-29 08:15 UTC, sindresorhus requested changes

2022-05-29 08:15 UTC, sindresorhus commented on index.d.ts
> +	__boolean__: Wether or not to fit all available space within the terminal.
index.d.ts and readme should be in sync.

2022-05-29 08:15 UTC, sindresorhus commented on index.d.ts
> +	__function__: Pass a callback function to control box dimensions.
This should be clearer about it being used to **modify** the calculated dimensions. And also some use-cases for it.

// @LitoMore

2022-06-07 11:08 UTC, Caesarovich commented
Should this be considered done ? :) @sindresorhus

2022-06-13 07:56 UTC, merged

2022-06-13 07:56 UTC, sindresorhus commented
Looks good :)